###############################################################################
#################################### commons #################################
###############################################################################
# 네임스페이스 생성
namespace:
  name: helastic
  annotations: {}
  labels: {
    istio-injection: enabled
  }

# host 부분에 도메인으로 등록할 주소 입력
istioGateway:
  servers:
    hosts:
      - "helastic.dev.sinsang.market"

# 자동 도메인 등록 (현재는 sandbox에서만 테스트 예정)
externalDns:
  domainFilter: "dev.sinsang.market"

# 서비스 이름 입력
fullnameOverride: helastic

# 서비스 포트 입력 (일반적으로 타겟포트도 동일하게 입력)
service:
  type: ClusterIP
  port: 9200
  targetPort: 9200

###############################################################################
####################  elastic-search / kibana values ##########################
###############################################################################

cluster: helastic
version: 7.15.2

nodeSets:
- name: master
  count: 1
  config:
    node.roles: ["master"]
    node.store.allow_mmap: false
    # xpack.security.enabled: false
  volumeClaimTemplates:
  - metadata:
      name: elasticsearch-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: gp2
  podTemplate:
    spec:
      initContainers:
      - name: init
        command: [ "sh", "-c"]
        args:
          - bin/elasticsearch-users useradd helastic -p helastic -r superuser;
            bin/elasticsearch-plugin install --batch analysis-nori repository-s3;
- name: data
  count: 1
  config:
    node.roles: ["data"]
    node.store.allow_mmap: false
    # xpack.security.enabled: false
  volumeClaimTemplates:
  - metadata:
      name: elasticsearch-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: gp2
  podTemplate:
    spec:
      initContainers:
      - name: init
        command: [ "sh", "-c"]
        args:
          - bin/elasticsearch-users useradd helastic -p helastic -r superuser;
            bin/elasticsearch-plugin install --batch analysis-nori repository-s3;
- name: coord
  count: 1
  config:
    node.roles: []
    node.store.allow_mmap: false
    # xpack.security.enabled: false
  volumeClaimTemplates:
  - metadata:
      name: elasticsearch-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: gp2
  podTemplate:
    spec:
      initContainers:
      - name: init
        command: [ "sh", "-c"]
        args:
          - bin/elasticsearch-users useradd helastic -p helastic -r superuser;
            bin/elasticsearch-plugin install --batch analysis-nori repository-s3;