apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ .Values.cluster }}
  namespace: {{ .Values.namespace.name }}
spec:
  version: {{ .Values.version }}
  nodeSets:
{{- toYaml .Values.nodeSets | nindent 4 }}