apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ .Values.cluster }}
  namespace: {{ .Values.namespace.name }}
spec:
  version: {{ .Values.version }}
  nodeSets:
{{- toYaml .Values.nodeSets | nindent 4 }}

---

apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: {{ .Values.cluster }}
  namespace: {{ .Values.namespace.name }}
spec:
  version: {{ .Values.version }}
  count: 1
  elasticsearchRef:
    name: {{ .Values.cluster }}