apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ .Values.cluster }}
  namespace: {{ .Values.namespace.name }}
spec:
  version: {{ .Values.version }}
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
{{- toYaml .Values.nodeSets | nindent 4 }}

---
## 요청을 coordnating node에 라우팅되도록 서비스 추가
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cluster }}-coord-http
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
    - name: http
      port: 9200
      targetPort: 9200
  selector:
    elasticsearch.k8s.elastic.co/cluster-name: {{ .Values.cluster }}
    elasticsearch.k8s.elastic.co/node-master: "false"
    elasticsearch.k8s.elastic.co/node-data: "false"
    elasticsearch.k8s.elastic.co/node-ingest: "false"
    elasticsearch.k8s.elastic.co/node-ml: "false"
    elasticsearch.k8s.elastic.co/node-transform: "false"